version: "3.9"
services:
  api:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - sqlite-data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
        
  client:
    build:
      context: ./client
    ports:
      - "3000:80"
        
volumes:
  sqlite-data:
