services:
  api:
    build:
      context: ./server/Wedding.API
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - sqlite-data:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - wedding-network
        
  client:
    build:
      context: ./client/wedding-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - API_URL=http://api:5001
    networks:
      - wedding-network
        
volumes:
  sqlite-data:
    
networks:
  wedding-network:
    driver: bridge
